language: python

dist: jammy

python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12

before_install:
  - git submodule update --remote

install:
  - pip install --upgrade -r requirements.txt

script:
  - py.test --cov=./

after_success:
  - flake8 --max-line-length 100 --ignore=E121,E123,E126,E221,E222,E225,E226,E242,E701,E702,E704,E731,W503,W504,F405,F841 .

notifications:
  email: false
