farmer = {
    'kb': '''
Farmer(Mac)
Rabbit(Pete)
Mother(MrsMac, Mac)
Mother(MrsRabbit, Pete)
(Rabbit(r) & Farmer(f)) ==> Hates(f, r)
(Mother(m, c)) ==> Loves(m, c)
(Mother(m, r) & Rabbit(r)) ==> Rabbit(m)
(Farmer(f)) ==> Human(f)
(Mother(m, h) & Human(h)) ==> Human(m)
''',
# Note that this order of conjuncts
# would result in infinite recursion:
# '(Human(h) & Mother(m, h)) ==> Human(m)'
    'queries':'''
Human(x)
Hates(x, y)
''',
#    'limit': 1,
}

weapons = {
    'kb': '''
(American(x) & Weapon(y) & Sells(x, y, z) & Hostile(z)) ==> Criminal(x)
Owns(Nono, M1)
Missile(M1)
(Missile(x) & Owns(Nono, x)) ==> Sells(West, x, Nono)
Missile(x) ==> Weapon(x)
Enemy(x, America) ==> Hostile(x)
American(West)
Enemy(Nono, America)
''',
    'queries':'''
Criminal(x)
''',
}

trackletes = {
    'kb': '''
    
    OneHundred(UsainBolt)
    OneHundred(JustnGatlin)
    OneHundred(AndreDeGrasse)
    OneHundred(AshtonEaton)
    OneHundred(KevinMayer)
    OneHundred(DamianWarner)
    TwoHundred(UsainBolt)
    TwoHundred(AndreDeGrasse)
    TwoHundred(ChristopheLemaitre)
    FourHundred(WaydevanNiedkirk)
    FourHundred(KiraniJames)
    FourHundred(LashawnMerrit)
    FourHundred(AshtonEaton)
    FourHundred(KevinMayer)
    FourHundred(DamianWarner)
    OneHundred(AsafaPowell)
    OneHundred(YohanBlake)
    OneHundred(NickelAsmeade)
    OneHundred(RyotaYamagata)
    OneHundred(ShotaIizuka)
    OneHundred(YoshihideKiryu)
    OneHundred(AsukaCambridge)
    OneHundred(AkeemHaynes)
    OneHundred(AaronBrowns)
    OneHundred(BrendonRodney)
    FirstLeg(AsafaPowell)
    SecondLeg(YohanBlake)
    ThirdLeg(NickelAsmeade)
    FourthLeg(UsainBolt)
    Relay(AsafaPowell,YohanBlake,NickelAsmeade,UsainBolt)
    FirstLeg(RyotaYamagata)
    SecondLeg(ShotaIizuka)
    ThirdLeg(YoshihideKiryu)
    FourthLeg(AsukaCambridge)
    Relay(RyotaYamagata,ShotaIizuka,YoshihideKiryu,AsukaCambridge)
    FirstLeg(AkeemHaynes)
    SecondLeg(AaronBrowns)
    ThirdLeg(BrendonRodney)
    FourthLeg(AndreDeGrasse)
    Relay(AkeemHaynes,AaronBrowns,BrendonRodney,AndreDeGrasse)
    (OneHundred(x) & OneHundred(y) & OneHundred(z) & OneHundred(w)) ==> AnyRelay(x,y,z,w)
    HighJump(DerekDrouin)
    HighJump(MutazBarshim)
    HighJump(BohdanBondarenko)
    HighJump(AshtonEaton)
    HighJump(KevinMayer)
    HighJump(DamianWarner)
    PoleVault(ThiagoBraz)
    PoleVault(RenaudLavillenie)
    PoleVault(SamKendricks)
    PoleVault(AshtonEaton)
    PoleVault(KevinMayer)
    PoleVault(DamianWarner)
    LongJump(JeffHenderson)
    LongJump(LuvoManyonga)
    LongJump(GregRutherford)
    LongJump(AshtonEaton)
    LongJump(KevinMayer)
    LongJump(DamianWarner)
    TripleJump(ChristianTaylor)
    TripleJump(WillClaye)
    TripleJump(DongBin)
    EightHundred(DavidRudisha)
    EightHundred(TaoufikMakhloufi)
    EightHundred(ClaytonMurphy)
    FifteenHundred(MattCentrowitz)
    FifteenHundred(TaoufikMakhloufi)
    FifteenHundred(NickWillis)
    FifteenHundred(AshtonEaton)
    FifteenHundred(KevinMayer)
    FifteenHundred(DamianWarner)
    FiveThousand(MoFarah)
    FiveThousand(PaulChelimo)
    FiveThousand(HagosGebrhiwet)
    TenThousand(MoFarah)
    TenThousand(PaulTanui)
    TenThousand(TamiratTola)
    SteepleChase(ConseslusKipruto)
    SteepleChase(EvanJager)
    SteepleChase(Mahiedine)
    ShotPut(RyanCrouser)
    ShotPut(JoeKovacs)
    ShotPut(TomasWalsh)
    ShotPut(AshtonEaton)
    ShotPut(KevinMayer)
    ShotPut(DamianWarner)
    Discus(ChristophHarting)
    Discus(PiotrMalachowski)
    Discus(DanielJasinski)
    Discus(AshtonEaton)
    Discus(KevinMayer)
    Discus(DamianWarner)
    Hammer(DilshodNazarov)
    Hammer(Ivantsikhan)
    Hammer(WojciechNowicki)
    Javelin(ThomasRohler)
    Javelin(JuliusYego)
    Javelin(KeshornWalcott)
    Javelin(AshtonEaton)
    Javelin(KevinMayer)
    Javelin(DamianWarner)
    OneTenHurdles(OmarMcleod)
    OneTenHurdles(OrlandoOrtega)
    OneTenHurdles(DimitriBascou)
    OneTenHurdles(AshtonEaton)
    OneTenHurdles(KevinMayer)
    OneTenHurdles(DamianWarner)
    FourHurdles(KerronClement)
    FourHurdles(BonifaceTumuti)
    FourHurdles(YasmaniCopello)
    
    OneHundred(x) ==> Sprinter(x)
    TwoHundred(x) ==> Sprinter(x)
    FourHundred(x) ==> Sprinter(x)
    
    HighJump(x) ==> Jumper(x)
    PoleVault(x) ==> Jumper(x)
    LongJump(x) ==> Jumper(x)
    TripleJump(x) ==> Jumper(x)
    ShotPut(x) ==> Thrower(x)
    Discus(x) ==> Thrower(x)
    Hammer(x) ==> Thrower(x)
    Javelin(x) ==> Thrower(x)
    OneTenHurdles(x) ==> Hurdler(x)
    FourHurdles(x) ==> Hurdler(x)
    EightHundred(x) ==> Runner(x)
    FifteenHundred(x) ==> Runner(x)
    FiveThousand(x) ==> Runner(x)
    TenThousand(x) ==> Runner(x)
    SteepleChase(x) ==> Runner(x)
    (HighJump(x) & PoleVault(x) & LongJump(x) & ShotPut(x) & Discus(x) & Javelin(x) & OneHundred(x) & FourHundred(x) & FifteenHundred(x) & OneTenHurdles(x)) ==> Decathlete(x)
    
    ''',
    'queries': '''
    OneHundred(x)
    PoleVault(x)
    Thrower(x)
    Jumper(x)
    Decathlete(x)
    Relay(x,y,z,w)
    AnyRelay(x,y,z,w)
    ''',
    'limit': 10
}

Examples = {
    'farmer': farmer,
    'weapons': weapons,
    'trackletes': trackletes,
}